kind: Service
apiVersion: v1
metadata:
  name: bl-train-server
spec:
  type: NodePort
  selector:
    app: bl-train-server
    tier: frontend
  ports:
    - name: rabbitmqweb
      port: 30000
      targetPort: 15672
      protocol: TCP
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl-train-server
spec:
  selector:
    matchLabels:
      app: bl-train-server
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: bl-train-server
        tier: frontend
        track: stable
    spec:
      containers:
        - name: bl-train-server
          image: jesperancinha/bl-train-server:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: queue
              containerPort: 5672
            - name: rabbitmqweb
              containerPort: 15672