version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/bl-central-server/bl-web-ui"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
