services:
  - docker:dind
stages:
  - build
  - qa
  - e2e
  - coverage
  - reporting
  - test
  - docker-compose
  - update

variables:
  MAVEN_CACHE_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CACHE_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  CODECOV_TOKEN: $CODECOV_TOKEN
  COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
  CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

image: maven:3-openjdk-18-slim

cache:
  paths:
    - .m2/repository/

before_script:
  - cat /etc/*-release
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install build-essential -y
  - bash latest-compose.sh

build cypress:
  image: node:18
  stage: build
  cache:
    - key: CYPRESS
      paths:
        - e2e/node_modules/
  script:
    - make build-npm-cypress
#  retry: 1
  except:
    - schedules

build node:
  image: node:18
  stage: build
  script:
    - make build-npm
  cache:
    - key: NODE_CACHE
      paths:
       - bl-bridge-server/bl-bridge-temperature-coap
       - bl-bridge-server/bl-bridge-humidity-mqtt
  except:
    - schedules

build maven:
  image: maven:3-openjdk-18-slim
  stage: build
  cache:
    - key: MAVEN_CACHE
      paths:
       - bl-central-server/bl-domain-repository/target
       - bl-central-server/bl-merchandise-data-collector/target
       - bl-central-server/bl-central-readings/bl-meters-readings-service/target
       - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
       - bl-central-server/bl-sensor-data-collector/target
       - bl-central-server/bl-web-app/target
  script:
    - apt install python3-pip -y
    - make build-maven
  except:
    - schedules

qa node:
  image: node:18
  stage: qa
  script:
    - yarn global add jest
    - make build-npm
  cache:
    - key: NODE_CACHE
      paths:
        - bl-bridge-server/bl-bridge-temperature-coap
        - bl-bridge-server/bl-bridge-humidity-mqtt
  except:
    - schedules
  needs:
    - build node

qa maven:
  image: maven:3-openjdk-18-slim
  stage: qa
  cache:
    - key: MAVEN_CACHE
      paths:
        - bl-central-server/bl-domain-repository/target
        - bl-central-server/bl-merchandise-data-collector/target
        - bl-central-server/bl-central-readings/bl-meters-readings-service/target
        - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
        - bl-central-server/bl-sensor-data-collector/target
        - bl-central-server/bl-web-app/target
  script:
    - make test-maven
  except:
    - schedules
  needs:
    - build maven

e2e electron:
  image: node:18
  stage: e2e
  script:
    - make dcup-action
    - make cypress-electron
    - make end-logs
  needs:
    - qa maven
    - qa node
    - build cypress
  cache:
    - key: MAVEN_CACHE
      paths:
        - bl-central-server/bl-domain-repository/target
        - bl-central-server/bl-merchandise-data-collector/target
        - bl-central-server/bl-central-readings/bl-meters-readings-service/target
        - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
        - bl-central-server/bl-sensor-data-collector/target
        - bl-central-server/bl-web-app/target
    - key: NODE_CACHE
      paths:
        - bl-bridge-server/bl-bridge-temperature-coap
        - bl-bridge-server/bl-bridge-humidity-mqtt
    - key: CYPRESS
      paths:
        - e2e/node_modules/
#  allow_failure: true
  timeout: 120m
#  retry: 1
  except:
    - schedules

e2e chrome:
  image: node:18
  stage: e2e
  script:
    - make dcup-action
    - make cypress-chrome
    - make end-logs
  needs:
    - qa maven
    - qa node
    - build cypress
  cache:
    - key: MAVEN_CACHE
      paths:
        - bl-central-server/bl-domain-repository/target
        - bl-central-server/bl-merchandise-data-collector/target
        - bl-central-server/bl-central-readings/bl-meters-readings-service/target
        - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
        - bl-central-server/bl-sensor-data-collector/target
        - bl-central-server/bl-web-app/target
    - key: NODE_CACHE
      paths:
        - bl-bridge-server/bl-bridge-temperature-coap
        - bl-bridge-server/bl-bridge-humidity-mqtt
    - key: CYPRESS
      paths:
        - e2e/node_modules/
  timeout: 120m
#  retry: 1
  except:
    - schedules

e2e firefox:
  image: node:18
  stage: e2e
  script:
    - make dcup-action
    - make cypress-firefox
    - make end-logs
  needs:
    - qa maven
    - qa node
    - build cypress
  cache:
    - key: MAVEN_CACHE
      paths:
        - bl-central-server/bl-domain-repository/target
        - bl-central-server/bl-merchandise-data-collector/target
        - bl-central-server/bl-central-readings/bl-meters-readings-service/target
        - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
        - bl-central-server/bl-sensor-data-collector/target
        - bl-central-server/bl-web-app/target
    - key: NODE_CACHE
      paths:
        - bl-bridge-server/bl-bridge-temperature-coap
        - bl-bridge-server/bl-bridge-humidity-mqtt
    - key: CYPRESS
      paths:
        - e2e/node_modules/
  timeout: 120m
#  allow_failure: true
#  retry: 1
  except:
    - schedules

e2e edge:
  image: node:18
  stage: e2e
  script:
    - make dcup-action
    - make cypress-edge
    - make end-logs
  needs:
    - qa maven
    - qa node
    - build cypress
  cache:
    - key: MAVEN_CACHE
      paths:
        - bl-central-server/bl-domain-repository/target
        - bl-central-server/bl-merchandise-data-collector/target
        - bl-central-server/bl-central-readings/bl-meters-readings-service/target
        - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
        - bl-central-server/bl-sensor-data-collector/target
        - bl-central-server/bl-web-app/target
    - key: NODE_CACHE
      paths:
        - bl-bridge-server/bl-bridge-temperature-coap
        - bl-bridge-server/bl-bridge-humidity-mqtt
    - key: CYPRESS
      paths:
        - e2e/node_modules/
  timeout: 120m
#  retry: 1
  except:
    - schedules

coverage python:
  image: maven:3-openjdk-18-slim
  stage: coverage
  script:
    - apt install python3-pip -y
    - pip3 install coverage
    - pip3 install pytest
    - make coverage-python
  only:
    - master
  needs:
    - e2e electron
    - e2e chrome
    - e2e firefox
    - e2e edge
  cache:
    - key: PYTHON_CACHE
      paths:
        - coverage-demo.json
        - coverage-simulation.json
  except:
    - schedules

coverage node:
  image: node:18
  stage: coverage
  script:
    - yarn global add jest
    - make coverage-npm
  only:
    - master
  needs:
    - e2e electron
    - e2e chrome
    - e2e firefox
    - e2e edge
  cache:
    - key: NODE_CACHE
      paths:
       - bl-bridge-server/bl-bridge-temperature-coap/coverage
       - bl-bridge-server/bl-bridge-humidity-mqtt/coverage
  except:
    - schedules

coverage maven:
  image: maven:3-openjdk-18-slim
  stage: coverage
  cache:
    - key: MAVEN_CACHE
      paths:
       - bl-central-server/bl-domain-repository/target
       - bl-central-server/bl-merchandise-data-collector/target
       - bl-central-server/bl-central-readings/bl-meters-readings-service/target
       - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
       - bl-central-server/bl-sensor-data-collector/target
       - bl-central-server/bl-web-app/target
  script:
    - make coverage-maven
  only:
    - master
  needs:
    - e2e electron
    - e2e chrome
    - e2e firefox
    - e2e edge
  except:
    - schedules

reporting:
  image: maven:3-openjdk-18-slim
  stage: 'reporting'
  cache:
    - key: MAVEN_CACHE
      paths:
       - bl-central-server/bl-domain-repository/target
       - bl-central-server/bl-merchandise-data-collector/target
       - bl-central-server/bl-central-readings/bl-meters-readings-service/target
       - bl-central-server/bl-central-readings/bl-passengers-readings-service/target
       - bl-central-server/bl-sensor-data-collector/target
       - bl-central-server/bl-web-app/target
    - key: NODE_CACHE
      paths:
       - bl-bridge-server/bl-bridge-temperature-coap/coverage
       - bl-bridge-server/bl-bridge-humidity-mqtt/coverage
    - key: PYTHON_CACHE
      paths:
       - coverage-demo.json
       - coverage-simulation.json
  script:
    - make report
  only:
    - master
  needs:
    - coverage maven
    - coverage node
    - coverage python
  except:
    - schedules


update-dependencies:
  image: renovate/renovate
  stage: update
  before_script: []
  script:
    - export RENOVATE_CONFIG=$(< renovate.json)
    - renovate
  only:
    - schedules
  needs: []
  timeout: 10m

