services:
  - docker:dind
stages:
  - build
  - coverage
  - reporting
  - verify
  - test
  - docker-compose
  - update

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  CODECOV_TOKEN: $CODECOV_TOKEN
  COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
  CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
image: maven:3-openjdk-16

cache:
  paths:
    - .m2/repository/
    - bl-central-server/bl-domain-repository/target
    - bl-central-server/bl-merchandise-data-collector/target
    - bl-central-server/bl-meters-readings-service/target
    - bl-central-server/bl-passengers-readings-service/target
    - bl-central-server/bl-sensor-data-collector/target
    - bl-central-server/bl-web-app/target
    - bl-bridge-server/bl-bridge-temperature-coap/node_modules
    - bl-bridge-server/bl-bridge-temperature-coap
    - bl-bridge-server/bl-bridge-humidity-mqtt/node_modules
    - bl-bridge-server/bl-bridge-humidity-mqtt
    - bl-demo-server
    - bl-simulation-data

.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master
verify:
  <<: *verify
#
# maven-build:
#   stage: build
#   script:
#     - if [ ! -f ci_settings.xml ];
#         then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
#       fi
#     - 'mvn clean install jacoco:prepare-agent package jacoco:report | grep -v "com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.wire"'
#
npm-bl-bridge-temperature-coap:
  image: node:6.3.0
  stage: build
  script:
    - apt update -y
    - apt install yarn -y
    - cd bl-bridge-server/bl-bridge-temperature-coap && yarn install && npm run test

npm-bl-bridge-humidity-mqtt:
  image: node:6.3.0
  stage: build
  script:
    - apt update -y
    - apt install yarn -y
    - cd bl-bridge-server/bl-bridge-humidity-mqtt && npm install && npm run test

coverage-python:
  image: maven:3.8-openjdk-17-slim
  stage: coverage
  script:
    - apt update -y
    - apt install python3-pip -y
    - pip3 install coverage
    - pip3 install pytest
    - coverage run --source=bl-demo-server -m pytest && coverage json -o coverage-demo.json
    - coverage run --source=bl-simulation-data -m pytest && coverage json -o coverage-simulation.json
  only:
    - master

coverage-node:
  image: maven:3.8-openjdk-17-slim
  stage: coverage
  script:
    - apt update -y
    - apt install npm -y
    - npm install jest --global
    - cd bl-bridge-server/bl-bridge-humidity-mqtt && jest --coverage
    - cd bl-bridge-server/bl-bridge-temperature-coap && jest --coverage
  only:
    - master

coverage-maven:
  image: maven:3.8-openjdk-17-slim
  stage: coverage
  script:
    - mvn clean install jacoco:prepare-agent package jacoco:report
  only:
    - master

reporting:
  image: maven:3.8-openjdk-17-slim
  stage: 'reporting'
  script:
    - mvn omni-coveragereporter:report
  only:
    - master

update-dependencies:
  image: renovate/renovate
  stage: update
  script:
    - export RENOVATE_CONFIG=$(< renovate.json)
    - renovate
  only:
    - master
