services:
  - docker:dind
stages:
  - build
  - coverage
  - coveralls
  - codecov
  - codacy
  - verify
  - test
  - docker-compose
  - update

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  CODECOV_TOKEN: $CODECOV_TOKEN
  COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
  CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
image: maven:3-openjdk-16

cache:
  paths:
    - .m2/repository/
    - bl-central-server/bl-domain-repository/target
    - bl-central-server/bl-merchandise-data-collector/target
    - bl-central-server/bl-meters-readings-service/target
    - bl-central-server/bl-passengers-readings-service/target
    - bl-central-server/bl-sensor-data-collector/target
    - bl-central-server/bl-web-app/target

.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master
verify:
  <<: *verify

maven-build:
  stage: build
  script:
    - if [ ! -f ci_settings.xml ];
        then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
      fi
    - 'mvn clean install jacoco:report | grep -v "com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.wire"'

npm-bl-bridge-temperature-coap:
  image: node:6.3.0
  stage: build
  script:
    - cd bl-bridge-server/bl-bridge-temperature-coap && npm run test

npm-bl-bridge-humidity-mqtt:
  image: node:6.3.0
  stage: build
  script:
    - cd bl-bridge-server/bl-bridge-humidity-mqtt && npm run test

build:
  stage: build
  script:
    - if [ ! -f ci_settings.xml ];
        then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
      fi
    - 'mvn clean install jacoco:prepare-agent package jacoco:report | grep -v "com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.wire"'

coveralls:
  stage: coverage
  script:
    - 'mvn omni-coveragereporter:report | grep -v "com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.wire"'
  only:
    - master
codecov:
  stage: coverage
  script:
    - 'bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN'
  only:
    - master
codacy:
  stage: coverage
  script:
    - 'bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find **/jacoco*.xml -printf ''-r %p '')'
  only:
    - master

update-dependencies:
  image: renovate/renovate
  stage: update
  script:
    - export RENOVATE_CONFIG=$(< renovate.json)
    - renovate
  only:
    - master

#docker-compose:
#  before_script:
#    - docker info
#  stage: docker-compose
#  script:
#    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#    - chmod +x /usr/local/bin/docker-compose
#    - docker-compose up -d --build --remove-orphans