services:
  - docker:dind
stages:
  - build
  - qa
  - e2e
  - coverage
  - reporting
  - test
  - docker-compose
  - update

variables:
  MAVEN_CACHE_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CACHE_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  CODECOV_TOKEN: $CODECOV_TOKEN
  COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
  CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

image: maven:3-openjdk-16

cache:
  paths:
    - .m2/repository/

before_script:
  - cat /etc/*-release
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install build-essential -y
  - bash latest-compose.sh

build node-sensors:
  image: node:18
  stage: build
  script:
    - make build-npm
  cache:
    - key: NODE_CACHE
      paths:
       - bl-bridge-server/bl-bridge-temperature-coap/coverage
       - bl-bridge-server/bl-bridge-humidity-mqtt/coverage
  except:
    - schedules

build maven:
  image: openjdk:19-alpine
  stage: build
  cache:
    - key: MAVEN_CACHE
      paths:
       - bl-central-server/bl-domain-repository/target
       - bl-central-server/bl-merchandise-data-collector/target
       - bl-central-server/bl-meters-readings-service/target
       - bl-central-server/bl-passengers-readings-service/target
       - bl-central-server/bl-sensor-data-collector/target
       - bl-central-server/bl-web-app/target
  script:
    - make build-maven
  except:
    - schedules

qa node-sensors:
  image: node:18
  stage: qa
  script:
    - make build-npm
  cache:
    - key: NODE_CACHE
      paths:
        - bl-bridge-server/bl-bridge-temperature-coap/coverage
        - bl-bridge-server/bl-bridge-humidity-mqtt/coverage
  except:
    - schedules
  needs:
    - build node-sensors

qa maven:
  image: openjdk:19-alpine
  stage: qa
  cache:
    - key: MAVEN_CACHE
      paths:
        - bl-central-server/bl-domain-repository/target
        - bl-central-server/bl-merchandise-data-collector/target
        - bl-central-server/bl-meters-readings-service/target
        - bl-central-server/bl-passengers-readings-service/target
        - bl-central-server/bl-sensor-data-collector/target
        - bl-central-server/bl-web-app/target
  script:
    - make test-maven
  except:
    - schedules
  needs:
    - qa maven

coverage python:
  image: openjdk:19-alpine
  stage: coverage
  script:
    - apt update -y
    - apt install python3-pip -y
    - pip3 install coverage
    - pip3 install pytest
    - make coverage-python
  only:
    - master
  needs: []
  cache:
    - key: PYTHON_CACHE
      paths:
        - 
        - coverage-demo.json
        - coverage-simulation.json
  except:
    - schedules

coverage node-sensors:
  image: node:18
  stage: coverage
  script:
    - make coverage-node
  only:
    - master
  needs:
    - qa node-sensors
  cache:
    - key: NODE_CACHE
      paths:
       - bl-bridge-server/bl-bridge-temperature-coap/coverage
       - bl-bridge-server/bl-bridge-humidity-mqtt/coverage
  except:
    - schedules

coverage maven:
  image: openjdk:19-alpine
  stage: coverage
  cache:
    - key: MAVEN_CACHE
      paths:
       - bl-central-server/bl-domain-repository/target
       - bl-central-server/bl-merchandise-data-collector/target
       - bl-central-server/bl-meters-readings-service/target
       - bl-central-server/bl-passengers-readings-service/target
       - bl-central-server/bl-sensor-data-collector/target
       - bl-central-server/bl-web-app/target
  script:
    - make coverage-maven
  only:
    - master
  needs:
    - qa maven
  except:
    - schedules

reporting:
  image: openjdk:19-alpine
  stage: 'reporting'
  cache:
    - key: MAVEN_CACHE
      paths:
       - bl-central-server/bl-domain-repository/target
       - bl-central-server/bl-merchandise-data-collector/target
       - bl-central-server/bl-meters-readings-service/target
       - bl-central-server/bl-passengers-readings-service/target
       - bl-central-server/bl-sensor-data-collector/target
       - bl-central-server/bl-web-app/target
    - key: NODE_CACHE
      paths:
       - bl-bridge-server/bl-bridge-temperature-coap/coverage
       - bl-bridge-server/bl-bridge-humidity-mqtt/coverage
    - key: PYTHON_CACHE
      paths:
       - coverage-demo.json
       - coverage-simulation.json
  script:
    - make report
  only:
    - master
  needs:
    - coverage maven
    - coverage node-sensors
    - coverage python
  except:
    - schedules


update-dependencies:
  image: renovate/renovate
  stage: update
  script:
    - export RENOVATE_CONFIG=$(< renovate.json)
    - renovate
  only:
    - schedules
  needs: []
  timeout: 10m

