version: "3.7"
services:
  bl_central_server:
    hostname: bl_central_server
    build:
      context: bl-central-server/.
    ports:
      - "15672:15672"
      - "5672:5672"

  bl_train_server:
    hostname: bl_train_server
    build:
      context: bl-train-server/.
    ports:
      - "15673:15672"
      - "5673:5672"

