version: "3.7"

services:

  bl_central_server:
    hostname: bl_central_server
    build:
      context: bl-central-server/bl-central-streaming/.
    ports:
      - "15672:15672"
      - "5672:5672"

  bl_train_01_rabbitmq_server:
    hostname: bl_train_01_rabbitmq_server
    build:
      context: bl-train-server/rabbitmq/.
    ports:
      - "15673:15672"
      - "5673:5672"

  bl_train_01_zookeeper_server:
    hostname: bl_train_01_zookeeper_server
    build:
      context: bl-train-server/zookeeper/.
    ports:
      - "2181:2181"

  bl_train_01_kafka_server:
    hostname: bl_train_01_kafka_server
    build:
      context: bl-train-server/kafka/.
    ports:
      - "9098:9098"
      - "9099:9099"
      - "9100:9100"
      - "9101:9101"
    depends_on:
      - bl_train_01_zookeeper_server

  bl_vehicle_01_server:
    hostname: bl_vehicle_01_server
    build:
      context: bl-vehicle-server/.
    ports:
      - "15675:15672"
      - "5675:5672"

  bl_bridge_01_humidity_mqtt_server:
    hostname: bl_bridge_01_humidity_mqtt_server
    build:
      context: bl-bridge-server/bl-bridge-humidity-mqtt/.

  bl_bridge_01_mosquitto_server:
    hostname: bl_bridge_01_mosquitto_server
    build:
      context: bl-bridge-server/mosquitto/.
    ports:
      - "1883:1883"

  bl_bridge_01_temperature_coap_server:
    hostname: bl_bridge_01_temperature_coap_server
    build:
      context: bl-bridge-server/bl-bridge-temperature-coap/.
    ports:
      - "5683:5683/udp"

  bl_bridge_01_rabbitmq_server:
    hostname: bl_bridge_01_rabbitmq_server
    build:
      context: bl-bridge-server/rabbitmq/.
    ports:
      - "5674:5672"
      - "15674:15672"

  bl_bridge_01_zookeeper_server:
    hostname: bl_bridge_01_zookeeper_server
    build:
      context: bl-bridge-server/zookeeper/.
    ports:
      - "2182:2181"

  bl_bridge_01_kafka_server:
    hostname: bl_bridge_01_kafka_server
    build:
      context: bl-bridge-server/kafka/.
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - bl_bridge_01_zookeeper_server

  bl_central_psql:
    hostname: bl_central_psql
    build:
      context: bl-central-server/bl-central-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=bllogistics
    ports:
      - "5432:5432"

  bl_central_server_apps:
    hostname: bl_central_server_apps
    build:
      context: bl-central-server/.
    ports:
      - "9000:9000"
    depends_on:
      - bl_central_psql
      - bl_central_server
      - bl_train_01_rabbitmq_server
      - bl_vehicle_01_server

  bl_central_cassandra:
    hostname: bl_central_cassandra
    build:
      context: bl-central-server/bl-central-cassandra/.
    ports:
      - "9042:9042"
      - "7199:7199"
