version: "3.7"

services:

  bl_central_server:
    hostname: bl_central_server
    container_name: bl_central_server
    build:
      context: bl-central-server/bl-central-streaming/.
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

  bl_train_01_rabbitmq_server:
    hostname: bl_train_01_rabbitmq_server
    container_name: bl_train_01_rabbitmq_server
    build:
      context: bl-train-server/rabbitmq/.
    ports:
      - "15673:15672"
      - "5673:5672"
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 250M

  bl_train_01_kafka_server:
    hostname: bl_train_01_kafka_server
    container_name: bl_train_01_kafka_server
    build:
      context: bl-train-server/kafka/.
    ports:
      - "9098:9098"
      - "9099:9099"
    deploy:
      resources:
        limits:
          memory: 900M
          cpus: '1'
        reservations:
          memory: 900M
          cpus: '1'

  bl_vehicle_01_server:
    hostname: bl_vehicle_01_server
    container_name: bl_vehicle_01_server
    build:
      context: bl-vehicle-server/.
    ports:
      - "15675:15672"
      - "5675:5672"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M

  bl_bridge_01_sensors_server:
    hostname: bl_bridge_01_sensors_server
    container_name: bl_bridge_01_sensors_server
    build:
      context: bl-bridge-server/.
    ports:
      - "5683:5683/udp"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  bl_bridge_01_mosquitto_server:
    hostname: bl_bridge_01_mosquitto_server
    container_name: bl_bridge_01_mosquitto_server
    build:
      context: bl-bridge-server/mosquitto/.
    ports:
      - "1883:1883"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 10M

  bl_bridge_01_rabbitmq_server:
    hostname: bl_bridge_01_rabbitmq_server
    container_name: bl_bridge_01_rabbitmq_server
    build:
      context: bl-bridge-server/rabbitmq/.
    ports:
      - "5674:5672"
      - "15674:15672"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 400M

  bl_bridge_01_kafka_server:
    hostname: bl_bridge_01_kafka_server
    container_name: bl_bridge_01_kafka_server
    build:
      context: bl-bridge-server/kafka/.
    ports:
      - "9092:9092"
      - "9093:9093"
    deploy:
      resources:
        limits:
          memory: 900M
          cpus: '1'
        reservations:
          memory: 900M
          cpus: '1'

  bl_central_psql:
    hostname: bl_central_psql
    container_name: bl_central_psql
    build:
      context: bl-central-server/bl-central-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=bllogistics
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  bl_central_server_apps:
    hostname: bl_central_server_apps
    container_name: bl_central_server_apps
    build:
      context: bl-central-server/.
    ports:
      - "9000:9000"
    depends_on:
      - bl_central_psql
      - bl_central_server
      - bl_train_01_rabbitmq_server
      - bl_vehicle_01_server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M

#  bl_central_cassandra:
#    hostname: bl_central_cassandra
#    container_name: bl_central_cassandra
#    build:
#      context: bl-central-server/bl-central-cassandra/.
#    ports:
#      - "9042:9042"
#    environment:
#      - "MAX_HEAP_SIZE=64M"
#      - "HEAP_NEWSIZE=64M"
#    healthcheck:
#      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
#      interval: 15s
#      timeout: 10s
#      retries: 10
#    deploy:
#      resources:
#        limits:
#          memory: 1000M
#          cpus: '1'
#        reservations:
#          memory: 1000M
#          cpus: '1'
