version: "3.7"
services:
  bl_central_server:
    hostname: bl_central_server
    build:
      context: bl-central-server/bl-rabbit-mq/.
    ports:
      - "15672:15672"
      - "5672:5672"

  bl_central_server_apps:
    hostname: bl_central_server_apps
    build:
      context: bl-central-server/.
    ports:
      - "9000:9000"

  bl_train_01_server:
    hostname: bl_train_01_server
    build:
      context: bl-train-server/.
    ports:
      - "15673:15672"
      - "5673:5672"

  bl_vehicle_01_server:
    hostname: bl_vehicle_01_server
    build:
      context: bl-vehicle-server/.
    ports:
      - "15675:15672"
      - "5675:5672"

  bl_bridge_01_server:
    hostname: bl_bridge_01_server
    build:
      context: bl-bridge-server/.
    ports:
      - "5674:5672"
      - "15674:15672"
      - "5683:5683/udp"
      - "1883:1883"
      - "7199:7199"
      - "7001:7001"
      - "7000:7000"
      - "9042:9042"
      - "9160:9160"
      - "61620:61620"
      - "61621:61621"
      - "8888:8888"
      - "9090:9090"
      - "9091:9091"
      - "9092:9092"

  postgres:
    hostname: postgres
    build:
      context: bl-central-server/docker-psql/.
    env_file:
      - bl-central-server/docker-psql/.env
    volumes:
      - ./docker-psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=bllogistics
    ports:
      - "5433:5432"
