version: "3.7"

services:

  bl_central_server:
    hostname: bl_central_server
    container_name: bl_central_server
    build:
      context: bl-central-server/bl-central-streaming/.
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M

  bl_central_kafka_server:
    hostname: bl_central_kafka_server
    container_name: bl_central_kafka_server
    build:
      context: bl-central-server/kafka/.
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M

  bl_train_01_rabbitmq_server:
    hostname: bl_train_01_rabbitmq_server
    container_name: bl_train_01_rabbitmq_server
    build:
      context: bl-train-server/rabbitmq/.
    deploy:
      resources:
        limits:
          memory: 250M
        reservations:
          memory: 250M

  bl_bridge_01_sensors_server:
    hostname: bl_bridge_01_sensors_server
    container_name: bl_bridge_01_sensors_server
    build:
      context: bl-bridge-server/.
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M

  bl_bridge_01_mosquitto_server:
    hostname: bl_bridge_01_mosquitto_server
    container_name: bl_bridge_01_mosquitto_server
    build:
      context: bl-bridge-server/mosquitto/.
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M

  bl_bridge_01_rabbitmq_server:
    hostname: bl_bridge_01_rabbitmq_server
    container_name: bl_bridge_01_rabbitmq_server
    build:
      context: bl-bridge-server/rabbitmq/.
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

  bl_central_psql:
    hostname: bl_central_psql
    container_name: bl_central_psql
    build:
      context: bl-central-server/bl-central-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=bllogistics
    deploy:
      resources:
        limits:
          memory: 100M

  bl_central_server_apps:
    hostname: bl_central_server_apps
    container_name: bl_central_server_apps
    build:
      context: bl-central-server/.
    depends_on:
      - bl_central_psql
      - bl_central_server
      - bl_train_01_rabbitmq_server
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 800M

  bl_central_cassandra:
    hostname: bl_central_cassandra
    container_name: bl_central_cassandra
    build:
      context: bl-central-server/bl-central-cassandra/.
    environment:
      - "MAX_HEAP_SIZE=64M"
      - "HEAP_NEWSIZE=64M"
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '1'
        reservations:
          memory: 500M
          cpus: '1'
