services:

  bl-central-server:
    ports:
      - "15672:15672"
      - "5672:5672"

  bl-readers:
    ports:
      - "4040:4040"
      - "4041:4041"

  bl-central-kafka-server:
    ports:
      - "9092:9092"
      - "9093:9093"

  bl-train-01-rabbitmq-server:
    ports:
      - "15673:15672"
      - "5673:5672"

  bl-bridge-01-sensors-server:
    ports:
      - "5683:5683/udp"

  bl-bridge-01-mosquitto_server:
    ports:
      - "1883:1883"

  bl-bridge-01-rabbitmq-server:
    ports:
      - "5674:5672"
      - "15674:15672"

  bl-central-psql:
    ports:
      - "5432:5432"

  bl-central-server-apps:
    ports:
      - "9000:9000"

  bl-central-cassandra:
    ports:
      - "9042:9042"
