kind: Service
apiVersion: v1
metadata:
  name: bl-central-server
spec:
  type: NodePort
  selector:
    app: bl-central-server
    tier: frontend
  ports:
    - name: http
      port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl-central-server
spec:
  selector:
    matchLabels:
      app: bl-central-server
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: bl-central-server
        tier: frontend
        track: stable
    spec:
      containers:
        - name: bl-central-server
          image: jesperancinha/bl-central-server:0.0.1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5672
            - name: rabbitmq
              containerPort: 15672