name: e2e-bridge-logistics-app

on: [push]

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Start Docker
        run: make dcup-full-action

      - name: Build Cypress
        run: make build-npm-cypress

      - name: Run Cypress
        run: make cypress-electron

      - name: Logs DC
        run: docker-compose logs

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Start Docker
        run: make dcup-full-action

      - name: Build Cypress
        run: make build-npm-cypress

      - name: Run Cypress
        run: make cypress-chrome

      - name: Logs DC
        run: docker-compose logs

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Start Docker
        run: make dcup-full-action

      - name: Build Cypress
        run: make build-npm-cypress

      - name: Run Cypress
        run: make cypress-firefox

      - name: Logs DC
        run: docker-compose logs

  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Start Docker
        run: make dcup-full-action

      - name: Build Cypress
        run: make build-npm-cypress

      - name: Run Cypress
        run: make cypress-edge

      - name: Logs DC
        run: docker-compose logs
