name: bridge-logistics-app

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'

    - name: Build Maven
      run:  make build-maven

    - name: Test Maven
      run:  make test-maven

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build Node JS and Test
      run: make build-npm && npm i -g jest && make test-node

    - name: Install Coverage Packages
      run: make install-coverage-python

    - name: Coverage reports
      run: make coverage-npm && make coverage-maven && make coverage-python

    - name: Coverage Reports Sending
      run: make report
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
