name: bridge-logistics-app-pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build Maven
      run:  make build-maven

    - name: Test Maven
      run:  make test-maven

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build Node JS and Test
      run: make build-npm && npm i -g jest && make test-node
